### PR TITLE
Fixing compatibility with python 3

### PR DESCRIPTION
**Pull request by Eraldo**
`has_key` was removed in python 3.

### CODE REVIEW

**Comment by Eraldo** [comment]
Thanks.
Can you please bump the version, so I can use PyPI. :)

**Comment by onepill** [comment]
@Eraldo done, version 0.0.8 is online

**Comment by Eraldo** [comment]
Awesome.. I will update my projects. ;)
Thank's for letting me know.

**Comment by Eraldo** [comment]
Oh.. I just saw that patch-2 is not yet merged.
Is there anything I can help with?

**Comment by onepill** [comment]
Hi Eraldo,

Sorry, just saw it, merged, please update to version 0.0.9.

Thanks

On Tue, Feb 16, 2016 at 1:56 AM, Eraldo Energy notifications@github.com
wrote:

> Oh.. I just saw that patch-2 is not yet merged.
> Is there anything I can help with?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/onepill/django-simplemde/pull/6#issuecomment-184324328
> .

## 

Siyuan Zhang

**Comment by Eraldo** [comment]
Great.. thank you. :)
Going back to main repo.

**Pull request merged**
